include:
  - project: 'papers/papers-internal/internal'
    file: '/.base-gitlab-ci.yml'

variables:
  TEST_TAG: $CI_PROJECT_NAME:test_$CI_COMMIT_SHA

stages:
  - build
  # - test
  - build_serve
  - publish
  - deploy

build:
  stage: build
  script:
    - docker build --target angular-build -t $TEST_TAG .
  tags:
    - docker

# test:
#   allow_failure: false
#   stage: test
#   script:
#     - docker run --name unit-$CI_COMMIT_SHA $TEST_TAG yarn test-ci
#     - docker run --name lint-$CI_COMMIT_SHA $TEST_TAG yarn lint-ci
#     - docker cp unit-$CI_COMMIT_SHA:/app/coverage/dapp-frontend/report-lcov/lcov.info lcov.info
#     - docker cp lint-$CI_COMMIT_SHA:/app/lintReport.json lintReport.json
#   after_script:
#     - docker rm -f unit-$CI_COMMIT_SHA || true
#     - docker rm -f lint-$CI_COMMIT_SHA || true
#   tags:
#     - docker
#   artifacts:
#     paths:
#       - lcov.info
#       - lintReport.json

.base_build:
  script:
    - docker build --build-arg RUN_ENV=$CI_ENVIRONMENT_NAME -t $GOOGLE_TAG-$CI_ENVIRONMENT_NAME .

build-tzbtc-dev:
  stage: build_serve
  script:
    - !reference [.base_build, script]
  only:
    - develop
  environment:
    name: tzbtc-dev

build-tzbtc-prod:
  stage: build_serve
  script:
    - !reference [.base_build, script]
  only:
    - main
  environment:
    name: tzbtc-prod

.base_publish:
  script:
    - docker tag $GOOGLE_TAG-$CI_ENVIRONMENT_NAME $TAG-$CI_ENVIRONMENT_NAME
    - docker tag $GOOGLE_TAG-$CI_ENVIRONMENT_NAME $TAG_LATEST-$CI_ENVIRONMENT_NAME
    - docker push $TAG-$CI_ENVIRONMENT_NAME
    - docker push $TAG_LATEST-$CI_ENVIRONMENT_NAME

publish-tzbtc-dev:
  stage: publish
  needs: ['build-tzbtc-dev']
  extends: .publish-dev
  variables:
    TAG: $GOOGLE_TAG_DEV
    TAG_LATEST: $GOOGLE_TAG_LATEST_DEV
  script:
    - !reference [.base_publish, script]
  only:
    - develop
  environment:
    name: tzbtc-dev
    action: prepare

publish-tzbtc-prod:
  stage: publish
  needs: ['build-tzbtc-prod']
  extends: .publish-prod
  variables:
    TAG: $GOOGLE_TAG
    TAG_LATEST: $GOOGLE_TAG_LATEST
  script:
    - !reference [.base_publish, script]
  environment:
    name: tzbtc-prod
    action: prepare

.base_deployment:
  script:
    - find k8s -type f -name \*.yaml -exec sed -i "s|__NAMESPACE_NAME__|"$NAMESPACE"|g" {} +
    - find k8s -type f -name \*.yaml -exec sed -i "s|__PROJECT_NAME__|"$PROJECT_NAME"|g" {} +
    - find k8s -type f -name \*.yaml -exec sed -i "s|__TO_BE_REPLACED_BY_IMAGE_TAG__|"$IMAGE_TAG-$CI_ENVIRONMENT_NAME"|g" {} +

    # ensure namespace is applied before the other kubernetes entities
    - kubectl apply -f k8s/common/namespace.yaml
    - kubectl apply -f k8s/$CI_ENVIRONMENT_NAME/ --recursive
    - kubectl apply -f k8s/common/ --recursive

k8s-deploy-tzbtc-dev:
  stage: deploy
  when: manual
  needs: ['publish-tzbtc-dev']
  extends: .run_dev
  variables:
    IMAGE_TAG: $GOOGLE_TAG_DEV
  script:
    - !reference [.base_deployment, script]
  only:
    - develop
  environment:
    name: tzbtc-dev

k8s-deploy-tzbtc-prod:
  stage: deploy
  when: manual
  needs: ['publish-tzbtc-prod']
  extends: .run_prod
  variables:
    IMAGE_TAG: $GOOGLE_TAG
  script:
    - !reference [.base_deployment, script]
  environment:
    name: tzbtc-prod
