apiVersion: v1
kind: Service
metadata:
  name: youves-__PROJECT_NAME__-service
  namespace: youves-__NAMESPACE_NAME__
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
  selector:
    app: youves-__PROJECT_NAME__
